<?php

namespace M2Performance\Service;

use M2Performance\Model\Recommendation;

class InfrastructureGenerator extends BaseScriptGenerator
{
    private array $recommendations;
    private array $config;

    public function __construct(array $recommendations, array $config = [])
    {
        $this->recommendations = $recommendations;
        $this->config = $config;
    }

    public function generate(string $type): string
    {
        return match($type) {
            'terraform' => $this->generateTerraform(),
            'ansible' => $this->generateAnsible(),
            'docker' => $this->generateDockerCompose(),
            default => throw new \InvalidArgumentException("Unknown infrastructure type: $type")
        };
    }

    private function generateTerraform(): string
    {
        $terraform = $this->getTerraformHeader();
        $terraform .= $this->getTerraformProviders();
        $terraform .= $this->getTerraformVariables();

        // Analyze recommendations to determine what infrastructure is needed
        $hasRedisIssues = $this->hasRecommendations('redis');
        $hasDatabaseIssues = $this->hasRecommendations('database');
        $hasCacheIssues = $this->hasRecommendations('cache', 'caching');
        $hasSecurityIssues = $this->hasRecommendations('security', 'api-security');

        // Generate infrastructure based on issues
        if ($hasRedisIssues || $hasCacheIssues) {
            $terraform .= $this->getTerraformRedis();
        }

        if ($hasDatabaseIssues) {
            $terraform .= $this->getTerraformDatabase();
        }

        if ($hasCacheIssues) {
            $terraform .= $this->getTerraformVarnish();
        }

        $terraform .= $this->getTerraformElasticsearch();
        $terraform .= $this->getTerraformAppServers();

        if ($hasSecurityIssues) {
            $terraform .= $this->getTerraformSecurity();
        }

        $terraform .= $this->getTerraformOutputs();

        return $terraform;
    }

    private function getTerraformHeader(): string
    {
        return <<<'TERRAFORM'
# Magento 2 Optimized Infrastructure
# Generated by M2 Performance Review Tool
# Date: {date}

terraform {
  required_version = ">= 1.0"
  
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
  
  backend "s3" {
    # Configure your backend
    # bucket = "your-terraform-state-bucket"
    # key    = "magento/terraform.tfstate"
    # region = "us-east-1"
  }
}

TERRAFORM;
    }

    private function getTerraformProviders(): string
    {
        return <<<'TERRAFORM'

provider "aws" {
  region = var.aws_region
  
  default_tags {
    tags = {
      Environment = var.environment
      Project     = "Magento2"
      ManagedBy   = "Terraform"
    }
  }
}

TERRAFORM;
    }

    private function getTerraformVariables(): string
    {
        return <<<'TERRAFORM'

# Variables
variable "aws_region" {
  description = "AWS region"
  type        = string
  default     = "us-east-1"
}

variable "environment" {
  description = "Environment name"
  type        = string
  default     = "production"
}

variable "vpc_cidr" {
  description = "VPC CIDR block"
  type        = string
  default     = "10.0.0.0/16"
}

variable "availability_zones" {
  description = "Availability zones"
  type        = list(string)
  default     = ["us-east-1a", "us-east-1b", "us-east-1c"]
}

variable "app_instance_type" {
  description = "EC2 instance type for Magento app servers"
  type        = string
  default     = "c5.xlarge"
}

variable "db_instance_class" {
  description = "RDS instance class"
  type        = string
  default     = "db.r5.xlarge"
}

# Networking
resource "aws_vpc" "main" {
  cidr_block           = var.vpc_cidr
  enable_dns_hostnames = true
  enable_dns_support   = true
  
  tags = {
    Name = "${var.environment}-magento-vpc"
  }
}

resource "aws_subnet" "public" {
  count                   = length(var.availability_zones)
  vpc_id                  = aws_vpc.main.id
  cidr_block              = cidrsubnet(var.vpc_cidr, 8, count.index)
  availability_zone       = var.availability_zones[count.index]
  map_public_ip_on_launch = true
  
  tags = {
    Name = "${var.environment}-public-${var.availability_zones[count.index]}"
    Type = "public"
  }
}

resource "aws_subnet" "private" {
  count             = length(var.availability_zones)
  vpc_id            = aws_vpc.main.id
  cidr_block        = cidrsubnet(var.vpc_cidr, 8, count.index + 10)
  availability_zone = var.availability_zones[count.index]
  
  tags = {
    Name = "${var.environment}-private-${var.availability_zones[count.index]}"
    Type = "private"
  }
}

TERRAFORM;
    }

    private function getTerraformRedis(): string
    {
        $config = $this->getRedisConfig();

        return <<<TERRAFORM

# Redis for Sessions and Cache
resource "aws_elasticache_replication_group" "sessions" {
  replication_group_id       = "\${var.environment}-magento-sessions"
  description                = "Redis for Magento sessions"
  engine                     = "redis"
  engine_version            = "7.0"
  node_type                 = "cache.r6g.large"
  num_cache_clusters        = 2
  port                      = 6379
  parameter_group_name      = aws_elasticache_parameter_group.redis_sessions.name
  subnet_group_name         = aws_elasticache_subnet_group.main.name
  security_group_ids        = [aws_security_group.redis.id]
  
  automatic_failover_enabled = true
  multi_az_enabled          = true
  
  at_rest_encryption_enabled = true
  transit_encryption_enabled = false  # Disable for performance if not required
  
  snapshot_retention_limit   = 5
  snapshot_window           = "03:00-05:00"
  maintenance_window        = "sun:05:00-sun:06:00"
  
  log_delivery_configuration {
    destination      = aws_cloudwatch_log_group.redis.name
    destination_type = "cloudwatch-logs"
    log_format       = "json"
    log_type         = "slow-log"
  }
  
  tags = {
    Name = "\${var.environment}-magento-sessions"
  }
}

resource "aws_elasticache_parameter_group" "redis_sessions" {
  name   = "\${var.environment}-redis-sessions"
  family = "redis7"
  
  # Optimized parameters based on recommendations
  parameter {
    name  = "timeout"
    value = "0"
  }
  
  parameter {
    name  = "tcp-keepalive"
    value = "60"
  }
  
  parameter {
    name  = "maxmemory-policy"
    value = "allkeys-lru"
  }
  
  parameter {
    name  = "lazyfree-lazy-eviction"
    value = "yes"
  }
  
  parameter {
    name  = "lazyfree-lazy-expire"
    value = "yes"
  }
  
  parameter {
    name  = "save"
    value = ""  # Disable RDB persistence for sessions
  }
}

resource "aws_elasticache_replication_group" "cache" {
  replication_group_id       = "\${var.environment}-magento-cache"
  description                = "Redis for Magento cache"
  engine                     = "redis"
  engine_version            = "7.0"
  node_type                 = "cache.r6g.xlarge"
  num_cache_clusters        = 2
  port                      = 6380
  parameter_group_name      = aws_elasticache_parameter_group.redis_cache.name
  subnet_group_name         = aws_elasticache_subnet_group.main.name
  security_group_ids        = [aws_security_group.redis.id]
  
  automatic_failover_enabled = true
  multi_az_enabled          = true
  
  at_rest_encryption_enabled = true
  transit_encryption_enabled = false
  
  snapshot_retention_limit   = 7
  snapshot_window           = "03:00-05:00"
  maintenance_window        = "sun:05:00-sun:06:00"
  
  tags = {
    Name = "\${var.environment}-magento-cache"
  }
}

resource "aws_elasticache_parameter_group" "redis_cache" {
  name   = "\${var.environment}-redis-cache"
  family = "redis7"
  
  parameter {
    name  = "maxmemory-policy"
    value = "allkeys-lru"
  }
  
  parameter {
    name  = "lazyfree-lazy-eviction"
    value = "yes"
  }
  
  # Enable RDB persistence for cache
  parameter {
    name  = "save"
    value = "900 1 300 10 60 10000"
  }
}

resource "aws_elasticache_subnet_group" "main" {
  name       = "\${var.environment}-redis"
  subnet_ids = aws_subnet.private[*].id
}

TERRAFORM;
    }

    private function getTerraformDatabase(): string
    {
        return <<<'TERRAFORM'

# RDS MySQL for Magento
resource "aws_db_instance" "magento" {
  identifier     = "${var.environment}-magento-db"
  engine         = "mysql"
  engine_version = "8.0"
  instance_class = var.db_instance_class
  
  allocated_storage       = 500
  max_allocated_storage   = 1000
  storage_type           = "gp3"
  storage_encrypted      = true
  iops                   = 12000
  storage_throughput     = 500
  
  db_name  = "magento"
  username = "magento"
  password = random_password.db_password.result
  
  vpc_security_group_ids = [aws_security_group.database.id]
  db_subnet_group_name   = aws_db_subnet_group.main.name
  
  backup_retention_period = 30
  backup_window          = "03:00-04:00"
  maintenance_window     = "sun:04:00-sun:05:00"
  
  enabled_cloudwatch_logs_exports = ["error", "general", "slowquery"]
  
  performance_insights_enabled          = true
  performance_insights_retention_period = 7
  
  parameter_group_name = aws_db_parameter_group.magento.name
  
  deletion_protection = true
  skip_final_snapshot = false
  final_snapshot_identifier = "${var.environment}-magento-db-final-${formatdate("YYYY-MM-DD-hhmm", timestamp())}"
  
  tags = {
    Name = "${var.environment}-magento-db"
  }
}

resource "aws_db_parameter_group" "magento" {
  name   = "${var.environment}-magento-mysql8"
  family = "mysql8.0"
  
  # Optimized parameters for Magento
  parameter {
    name  = "max_connections"
    value = "500"
  }
  
  parameter {
    name  = "innodb_buffer_pool_size"
    value = "{DBInstanceClassMemory*3/4}"
  }
  
  parameter {
    name  = "innodb_log_file_size"
    value = "2147483648"  # 2GB
  }
  
  parameter {
    name  = "innodb_flush_log_at_trx_commit"
    value = "2"
  }
  
  parameter {
    name  = "innodb_flush_method"
    value = "O_DIRECT"
  }
  
  parameter {
    name  = "query_cache_type"
    value = "0"  # Disabled in MySQL 8.0
  }
  
  parameter {
    name  = "slow_query_log"
    value = "1"
  }
  
  parameter {
    name  = "long_query_time"
    value = "2"
  }
  
  parameter {
    name  = "log_queries_not_using_indexes"
    value = "1"
  }
}

resource "aws_db_subnet_group" "main" {
  name       = "${var.environment}-magento"
  subnet_ids = aws_subnet.private[*].id
  
  tags = {
    Name = "${var.environment}-magento-db-subnet"
  }
}

resource "random_password" "db_password" {
  length  = 32
  special = true
}

# Store password in Secrets Manager
resource "aws_secretsmanager_secret" "db_password" {
  name = "${var.environment}-magento-db-password"
}

resource "aws_secretsmanager_secret_version" "db_password" {
  secret_id     = aws_secretsmanager_secret.db_password.id
  secret_string = random_password.db_password.result
}

TERRAFORM;
    }

    private function getTerraformVarnish(): string
    {
        return <<<'TERRAFORM'

# Varnish Cache Servers
resource "aws_launch_template" "varnish" {
  name_prefix   = "${var.environment}-varnish-"
  image_id      = data.aws_ami.ubuntu.id
  instance_type = "c5.large"
  
  vpc_security_group_ids = [aws_security_group.varnish.id]
  
  user_data = base64encode(templatefile("${path.module}/userdata/varnish.sh", {
    environment = var.environment
    backend_alb = aws_lb.app.dns_name
  }))
  
  block_device_mappings {
    device_name = "/dev/sda1"
    
    ebs {
      volume_size           = 50
      volume_type          = "gp3"
      delete_on_termination = true
      encrypted            = true
    }
  }
  
  metadata_options {
    http_endpoint = "enabled"
    http_tokens   = "required"
  }
  
  tag_specifications {
    resource_type = "instance"
    
    tags = {
      Name = "${var.environment}-varnish"
    }
  }
}

resource "aws_autoscaling_group" "varnish" {
  name                = "${var.environment}-varnish"
  vpc_zone_identifier = aws_subnet.public[*].id
  target_group_arns   = [aws_lb_target_group.varnish.arn]
  health_check_type   = "ELB"
  health_check_grace_period = 300
  
  min_size         = 2
  max_size         = 4
  desired_capacity = 2
  
  launch_template {
    id      = aws_launch_template.varnish.id
    version = "$Latest"
  }
  
  tag {
    key                 = "Name"
    value               = "${var.environment}-varnish"
    propagate_at_launch = true
  }
}

TERRAFORM;
    }

    private function getTerraformElasticsearch(): string
    {
        return <<<'TERRAFORM'

# OpenSearch (Elasticsearch) for catalog search
resource "aws_opensearch_domain" "magento" {
  domain_name    = "${var.environment}-magento-search"
  engine_version = "OpenSearch_2.9"
  
  cluster_config {
    instance_type            = "r5.large.search"
    instance_count          = 3
    zone_awareness_enabled  = true
    
    zone_awareness_config {
      availability_zone_count = 3
    }
  }
  
  ebs_options {
    ebs_enabled = true
    volume_size = 100
    volume_type = "gp3"
    iops        = 3000
    throughput  = 125
  }
  
  node_to_node_encryption {
    enabled = true
  }
  
  encrypt_at_rest {
    enabled = true
  }
  
  domain_endpoint_options {
    enforce_https       = true
    tls_security_policy = "Policy-Min-TLS-1-2-2019-07"
  }
  
  advanced_options = {
    "rest.action.multi.allow_explicit_index" = "true"
    "indices.fielddata.cache.size"          = "40"
    "indices.query.bool.max_clause_count"   = "2048"
  }
  
  log_publishing_options {
    cloudwatch_log_group_arn = aws_cloudwatch_log_group.opensearch.arn
    log_type                 = "INDEX_SLOW_LOGS"
  }
  
  tags = {
    Name = "${var.environment}-magento-search"
  }
}

resource "aws_cloudwatch_log_group" "opensearch" {
  name              = "/aws/opensearch/${var.environment}-magento"
  retention_in_days = 7
}

TERRAFORM;
    }

    private function getTerraformAppServers(): string
    {
        return <<<'TERRAFORM'

# Application Load Balancer
resource "aws_lb" "main" {
  name               = "${var.environment}-magento"
  internal           = false
  load_balancer_type = "application"
  security_groups    = [aws_security_group.alb.id]
  subnets            = aws_subnet.public[*].id
  
  enable_deletion_protection = true
  enable_http2              = true
  enable_drop_invalid_header_fields = true
  
  tags = {
    Name = "${var.environment}-magento-alb"
  }
}

# Magento App Servers
resource "aws_launch_template" "app" {
  name_prefix   = "${var.environment}-magento-app-"
  image_id      = data.aws_ami.ubuntu.id
  instance_type = var.app_instance_type
  
  vpc_security_group_ids = [aws_security_group.app.id]
  
  user_data = base64encode(templatefile("${path.module}/userdata/magento.sh", {
    environment     = var.environment
    redis_sessions  = aws_elasticache_replication_group.sessions.primary_endpoint_address
    redis_cache     = aws_elasticache_replication_group.cache.primary_endpoint_address
    database_host   = aws_db_instance.magento.address
    database_name   = aws_db_instance.magento.db_name
    database_user   = aws_db_instance.magento.username
    database_pass   = random_password.db_password.result
    opensearch_host = aws_opensearch_domain.magento.endpoint
  }))
  
  block_device_mappings {
    device_name = "/dev/sda1"
    
    ebs {
      volume_size           = 100
      volume_type          = "gp3"
      iops                 = 3000
      throughput           = 125
      delete_on_termination = true
      encrypted            = true
    }
  }
  
  metadata_options {
    http_endpoint = "enabled"
    http_tokens   = "required"
  }
  
  tag_specifications {
    resource_type = "instance"
    
    tags = {
      Name = "${var.environment}-magento-app"
    }
  }
}

resource "aws_autoscaling_group" "app" {
  name                = "${var.environment}-magento-app"
  vpc_zone_identifier = aws_subnet.private[*].id
  target_group_arns   = [aws_lb_target_group.app.arn]
  health_check_type   = "ELB"
  health_check_grace_period = 600
  
  min_size         = 2
  max_size         = 10
  desired_capacity = 3
  
  launch_template {
    id      = aws_launch_template.app.id
    version = "$Latest"
  }
  
  enabled_metrics = [
    "GroupMinSize",
    "GroupMaxSize",
    "GroupDesiredCapacity",
    "GroupInServiceInstances",
    "GroupTotalInstances"
  ]
  
  tag {
    key                 = "Name"
    value               = "${var.environment}-magento-app"
    propagate_at_launch = true
  }
}

# Auto Scaling Policies
resource "aws_autoscaling_policy" "scale_up" {
  name                   = "${var.environment}-magento-scale-up"
  scaling_adjustment     = 2
  adjustment_type        = "ChangeInCapacity"
  cooldown              = 300
  autoscaling_group_name = aws_autoscaling_group.app.name
}

resource "aws_autoscaling_policy" "scale_down" {
  name                   = "${var.environment}-magento-scale-down"
  scaling_adjustment     = -1
  adjustment_type        = "ChangeInCapacity"
  cooldown              = 300
  autoscaling_group_name = aws_autoscaling_group.app.name
}

resource "aws_cloudwatch_metric_alarm" "cpu_high" {
  alarm_name          = "${var.environment}-magento-cpu-high"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = "2"
  metric_name        = "CPUUtilization"
  namespace          = "AWS/EC2"
  period             = "300"
  statistic          = "Average"
  threshold          = "80"
  alarm_description  = "This metric monitors CPU utilization"
  alarm_actions      = [aws_autoscaling_policy.scale_up.arn]
  
  dimensions = {
    AutoScalingGroupName = aws_autoscaling_group.app.name
  }
}

TERRAFORM;
    }

    private function getTerraformSecurity(): string
    {
        return <<<'TERRAFORM'

# Security Groups
resource "aws_security_group" "alb" {
  name        = "${var.environment}-magento-alb"
  description = "Security group for ALB"
  vpc_id      = aws_vpc.main.id
  
  ingress {
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }
  
  ingress {
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }
  
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
  
  tags = {
    Name = "${var.environment}-magento-alb-sg"
  }
}

resource "aws_security_group" "varnish" {
  name        = "${var.environment}-magento-varnish"
  description = "Security group for Varnish"
  vpc_id      = aws_vpc.main.id
  
  ingress {
    from_port       = 80
    to_port         = 80
    protocol        = "tcp"
    security_groups = [aws_security_group.alb.id]
  }
  
  ingress {
    from_port       = 6082
    to_port         = 6082
    protocol        = "tcp"
    security_groups = [aws_security_group.app.id]
    description     = "Varnish admin"
  }
  
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
  
  tags = {
    Name = "${var.environment}-magento-varnish-sg"
  }
}

resource "aws_security_group" "app" {
  name        = "${var.environment}-magento-app"
  description = "Security group for Magento app servers"
  vpc_id      = aws_vpc.main.id
  
  ingress {
    from_port       = 80
    to_port         = 80
    protocol        = "tcp"
    security_groups = [aws_security_group.varnish.id]
  }
  
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
  
  tags = {
    Name = "${var.environment}-magento-app-sg"
  }
}

resource "aws_security_group" "redis" {
  name        = "${var.environment}-magento-redis"
  description = "Security group for Redis"
  vpc_id      = aws_vpc.main.id
  
  ingress {
    from_port       = 6379
    to_port         = 6380
    protocol        = "tcp"
    security_groups = [aws_security_group.app.id]
  }
  
  tags = {
    Name = "${var.environment}-magento-redis-sg"
  }
}

resource "aws_security_group" "database" {
  name        = "${var.environment}-magento-db"
  description = "Security group for RDS"
  vpc_id      = aws_vpc.main.id
  
  ingress {
    from_port       = 3306
    to_port         = 3306
    protocol        = "tcp"
    security_groups = [aws_security_group.app.id]
  }
  
  tags = {
    Name = "${var.environment}-magento-db-sg"
  }
}

# WAF for API Protection
resource "aws_wafv2_web_acl" "api_protection" {
  name  = "${var.environment}-magento-api-waf"
  scope = "REGIONAL"
  
  default_action {
    allow {}
  }
  
  # Rate limiting rule
  rule {
    name     = "RateLimitRule"
    priority = 1
    
    action {
      block {}
    }
    
    statement {
      rate_based_statement {
        limit              = 2000
        aggregate_key_type = "IP"
        
        scope_down_statement {
          regex_pattern_set_reference_statement {
            arn = aws_wafv2_regex_pattern_set.api_paths.arn
            
            field_to_match {
              uri_path {}
            }
            
            text_transformation {
              priority = 0
              type     = "NONE"
            }
          }
        }
      }
    }
    
    visibility_config {
      cloudwatch_metrics_enabled = true
      metric_name               = "RateLimitRule"
      sampled_requests_enabled   = true
    }
  }
  
  visibility_config {
    cloudwatch_metrics_enabled = true
    metric_name               = "${var.environment}-magento-waf"
    sampled_requests_enabled   = true
  }
  
  tags = {
    Name = "${var.environment}-magento-api-waf"
  }
}

resource "aws_wafv2_regex_pattern_set" "api_paths" {
  name        = "${var.environment}-magento-api-paths"
  scope       = "REGIONAL"
  
  regular_expression {
    regex_string = "^/rest/.*"
  }
  
  regular_expression {
    regex_string = "^/graphql.*"
  }
  
  regular_expression {
    regex_string = "^/soap/.*"
  }
  
  tags = {
    Name = "${var.environment}-magento-api-paths"
  }
}

TERRAFORM;
    }

    private function getTerraformOutputs(): string
    {
        return <<<'TERRAFORM'

# Outputs
output "alb_dns_name" {
  description = "DNS name of the load balancer"
  value       = aws_lb.main.dns_name
}

output "redis_sessions_endpoint" {
  description = "Redis sessions primary endpoint"
  value       = aws_elasticache_replication_group.sessions.primary_endpoint_address
}

output "redis_cache_endpoint" {
  description = "Redis cache primary endpoint"
  value       = aws_elasticache_replication_group.cache.primary_endpoint_address
}

output "database_endpoint" {
  description = "RDS database endpoint"
  value       = aws_db_instance.magento.endpoint
}

output "opensearch_endpoint" {
  description = "OpenSearch domain endpoint"
  value       = aws_opensearch_domain.magento.endpoint
}

output "db_password_secret_arn" {
  description = "ARN of the database password secret"
  value       = aws_secretsmanager_secret.db_password.arn
}

# Data sources
data "aws_ami" "ubuntu" {
  most_recent = true
  owners      = ["099720109477"]  # Canonical
  
  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"]
  }
  
  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

TERRAFORM;
    }

    private function generateAnsible(): string
    {
        $ansible = $this->getAnsibleHeader();

        // Add tasks based on recommendations
        $hasRedisIssues = $this->hasRecommendations('redis');
        $hasOpcacheIssues = $this->hasRecommendations('opcache');
        $hasSecurityIssues = $this->hasRecommendations('security');
        $hasCacheIssues = $this->hasRecommendations('cache', 'caching');

        if ($hasRedisIssues) {
            $ansible .= $this->getAnsibleRedisOptimization();
        }

        if ($hasOpcacheIssues) {
            $ansible .= $this->getAnsibleOpcacheOptimization();
        }

        if ($hasSecurityIssues) {
            $ansible .= $this->getAnsibleSecurityHardening();
        }

        if ($hasCacheIssues) {
            $ansible .= $this->getAnsibleVarnishConfiguration();
        }

        $ansible .= $this->getAnsibleMagentoOptimization();

        return $ansible;
    }

    private function getAnsibleHeader(): string
    {
        return <<<'YAML'
---
# Magento 2 Performance Optimization Playbook
# Generated by M2 Performance Review Tool

- name: Magento 2 Performance Optimization
  hosts: all
  become: yes
  vars:
    magento_root: /var/www/magento2
    php_version: "8.1"
    
  tasks:
YAML;
    }

    private function getAnsibleRedisOptimization(): string
    {
        return <<<'YAML'

    - name: Configure Redis for optimal performance
      block:
        - name: Install Redis
          apt:
            name: redis-server
            state: present
            update_cache: yes
        
        - name: Configure Redis for sessions
          blockinfile:
            path: /etc/redis/redis.conf
            block: |
              # Performance optimizations
              maxmemory 2gb
              maxmemory-policy allkeys-lru
              
              # Disable persistence for sessions
              save ""
              appendonly no
              
              # Connection settings
              timeout 0
              tcp-keepalive 60
              tcp-backlog 511
              
              # Performance tuning
              lazyfree-lazy-eviction yes
              lazyfree-lazy-expire yes
              lazyfree-lazy-server-del yes
              replica-lazy-flush yes
              
              # Slow log
              slowlog-log-slower-than 10000
              slowlog-max-len 128
          notify: restart redis
        
        - name: Configure Redis for cache (separate instance)
          copy:
            dest: /etc/redis/redis-cache.conf
            content: |
              include /etc/redis/redis.conf
              port 6380
              pidfile /var/run/redis/redis-server-cache.pid
              logfile /var/log/redis/redis-server-cache.log
              dbfilename dump-cache.rdb
              
              # Enable persistence for cache
              save 900 1
              save 300 10
              save 60 10000
              
              maxmemory 4gb
              maxmemory-policy allkeys-lru
        
        - name: Create systemd service for cache instance
          copy:
            dest: /etc/systemd/system/redis-cache.service
            content: |
              [Unit]
              Description=Redis Cache Server
              After=network.target
              
              [Service]
              Type=notify
              ExecStart=/usr/bin/redis-server /etc/redis/redis-cache.conf --supervised systemd
              ExecStop=/usr/bin/redis-cli -p 6380 shutdown
              TimeoutStopSec=0
              Restart=on-failure
              
              [Install]
              WantedBy=multi-user.target
        
        - name: Start and enable Redis services
          systemd:
            name: "{{ item }}"
            state: started
            enabled: yes
            daemon_reload: yes
          loop:
            - redis
            - redis-cache
    
    - name: Update Magento Redis configuration
      template:
        src: redis-config.php.j2
        dest: "{{ magento_root }}/app/etc/env.php.redis"
        backup: yes
      notify: clear magento cache

YAML;
    }

    private function getAnsibleOpcacheOptimization(): string
    {
        return <<<'YAML'

    - name: Optimize PHP OPcache
      block:
        - name: Configure OPcache settings
          ini_file:
            path: "/etc/php/{{ php_version }}/fpm/conf.d/10-opcache.ini"
            section: opcache
            option: "{{ item.option }}"
            value: "{{ item.value }}"
          loop:
            - { option: 'opcache.enable', value: '1' }
            - { option: 'opcache.enable_cli', value: '1' }
            - { option: 'opcache.memory_consumption', value: '512' }
            - { option: 'opcache.interned_strings_buffer', value: '64' }
            - { option: 'opcache.max_accelerated_files', value: '60000' }
            - { option: 'opcache.validate_timestamps', value: '0' }
            - { option: 'opcache.revalidate_freq', value: '0' }
            - { option: 'opcache.save_comments', value: '1' }
            - { option: 'opcache.enable_file_override', value: '0' }
            - { option: 'opcache.optimization_level', value: '0x7FFEBFFF' }
            - { option: 'opcache.huge_code_pages', value: '1' }
            - { option: 'opcache.preload_user', value: 'www-data' }
          notify: restart php-fpm
        
        - name: Configure PHP-FPM pool
          template:
            src: php-fpm-pool.conf.j2
            dest: "/etc/php/{{ php_version }}/fpm/pool.d/magento.conf"
          notify: restart php-fpm

YAML;
    }

    private function getAnsibleSecurityHardening(): string
    {
        return <<<'YAML'

    - name: Security hardening
      block:
        - name: Set secure file permissions
          file:
            path: "{{ item.path }}"
            mode: "{{ item.mode }}"
            owner: www-data
            group: www-data
          loop:
            - { path: "{{ magento_root }}/app/etc", mode: '0750' }
            - { path: "{{ magento_root }}/app/etc/env.php", mode: '0640' }
            - { path: "{{ magento_root }}/var", mode: '0750' }
            - { path: "{{ magento_root }}/generated", mode: '0750' }
            - { path: "{{ magento_root }}/pub/static", mode: '0750' }
            - { path: "{{ magento_root }}/pub/media", mode: '0750' }
        
        - name: Configure Nginx security headers
          blockinfile:
            path: /etc/nginx/snippets/security-headers.conf
            create: yes
            block: |
              add_header X-Frame-Options "SAMEORIGIN" always;
              add_header X-Content-Type-Options "nosniff" always;
              add_header X-XSS-Protection "1; mode=block" always;
              add_header Referrer-Policy "strict-origin-when-cross-origin" always;
              add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
              add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;
        
        - name: Configure Nginx rate limiting
          blockinfile:
            path: /etc/nginx/conf.d/rate-limiting.conf
            create: yes
            block: |
              # Rate limiting zones
              limit_req_zone $binary_remote_addr zone=general:10m rate=10r/s;
              limit_req_zone $binary_remote_addr zone=api:10m rate=20r/s;
              limit_req_zone $binary_remote_addr zone=search:10m rate=5r/s;
              limit_req_zone $binary_remote_addr zone=checkout:10m rate=3r/s;
              limit_req_zone $binary_remote_addr zone=admin:10m rate=5r/m;
              
              # Connection limiting
              limit_conn_zone $binary_remote_addr zone=addr:10m;
              limit_conn addr 10;
          notify: reload nginx
        
        - name: Secure admin URL
          lineinfile:
            path: "{{ magento_root }}/app/etc/env.php"
            regexp: "'frontName' => '[^']+'"
            line: "    'frontName' => '{{ admin_url | default('admin_' + 9999999999999999 | random | string) }}'"
          when: secure_admin_url | default(true)

YAML;
    }

    private function getAnsibleVarnishConfiguration(): string
    {
        return <<<'YAML'

    - name: Configure Varnish Cache
      block:
        - name: Install Varnish
          apt:
            name: varnish
            state: present
        
        - name: Configure Varnish VCL
          template:
            src: varnish.vcl.j2
            dest: /etc/varnish/default.vcl
            backup: yes
          notify: restart varnish
        
        - name: Configure Varnish service
          lineinfile:
            path: /etc/systemd/system/varnish.service.d/override.conf
            create: yes
            line: |
              [Service]
              ExecStart=
              ExecStart=/usr/bin/varnish -a :80 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,2g -p thread_pools=4 -p thread_pool_min=200 -p thread_pool_max=4000 -p thread_pool_add_delay=2 -p cli_timeout=25 -p feature=+esi_ignore_https -p default_ttl=86400 -p default_grace=86400
          notify: 
            - daemon reload
            - restart varnish

YAML;
    }

    private function getAnsibleMagentoOptimization(): string
    {
        return <<<'YAML'

    - name: Magento application optimization
      block:
        - name: Enable all Magento cache types
          command: "php {{ magento_root }}/bin/magento cache:enable"
          become_user: www-data
        
        - name: Set production mode
          command: "php {{ magento_root }}/bin/magento deploy:mode:set production --skip-compilation"
          become_user: www-data
          when: magento_mode | default('production') == 'production'
        
        - name: Configure Magento optimizations
          shell: |
            php {{ magento_root }}/bin/magento config:set dev/js/merge_files 1
            php {{ magento_root }}/bin/magento config:set dev/js/minify_files 1
            php {{ magento_root }}/bin/magento config:set dev/js/enable_js_bundling 1
            php {{ magento_root }}/bin/magento config:set dev/css/merge_css_files 1
            php {{ magento_root }}/bin/magento config:set dev/css/minify_files 1
            php {{ magento_root }}/bin/magento config:set dev/template/minify_html 1
            php {{ magento_root }}/bin/magento config:set catalog/search/engine elasticsearch7
            php {{ magento_root }}/bin/magento config:set system/full_page_cache/caching_application 2
          become_user: www-data
        
        - name: Run Magento compilation
          command: "php {{ magento_root }}/bin/magento setup:di:compile"
          become_user: www-data
        
        - name: Deploy static content
          command: "php {{ magento_root }}/bin/magento setup:static-content:deploy -f"
          become_user: www-data
        
        - name: Reindex all indexers
          command: "php {{ magento_root }}/bin/magento indexer:reindex"
          become_user: www-data
        
        - name: Set indexers to update by schedule
          shell: "php {{ magento_root }}/bin/magento indexer:set-mode schedule"
          become_user: www-data
    
    - name: Configure cron jobs
      block:
        - name: Install Magento cron jobs
          command: "php {{ magento_root }}/bin/magento cron:install"
          become_user: www-data
        
        - name: Ensure cron service is running
          service:
            name: cron
            state: started
            enabled: yes
  
  handlers:
    - name: restart redis
      service:
        name: redis-server
        state: restarted
    
    - name: restart php-fpm
      service:
        name: "php{{ php_version }}-fpm"
        state: restarted
    
    - name: reload nginx
      service:
        name: nginx
        state: reloaded
    
    - name: restart varnish
      service:
        name: varnish
        state: restarted
    
    - name: daemon reload
      systemd:
        daemon_reload: yes
    
    - name: clear magento cache
      command: "php {{ magento_root }}/bin/magento cache:clean"
      become_user: www-data

YAML;
    }

    private function generateDockerCompose(): string
    {
        $hasRedis = $this->hasRecommendations('redis');
        $hasElasticsearch = $this->hasRecommendations('indexing');
        $hasVarnish = $this->hasRecommendations('cache', 'caching');

        $compose = $this->getDockerComposeHeader();
        $compose .= $this->getDockerComposeMagento();

        if ($hasRedis) {
            $compose .= $this->getDockerComposeRedis();
        }

        $compose .= $this->getDockerComposeDatabase();

        if ($hasElasticsearch) {
            $compose .= $this->getDockerComposeElasticsearch();
        }

        if ($hasVarnish) {
            $compose .= $this->getDockerComposeVarnish();
        }

        $compose .= $this->getDockerComposeNetworks();
        $compose .= $this->getDockerComposeVolumes();

        return $compose;
    }

    private function getDockerComposeHeader(): string
    {
        return <<<'YAML'
version: '3.8'

# Magento 2 Optimized Docker Compose Configuration
# Generated by M2 Performance Review Tool

services:
YAML;
    }

    private function getDockerComposeMagento(): string
    {
        return <<<'YAML'

  magento:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: "8.1"
    container_name: magento_app
    environment:
      - MAGE_MODE=production
      - PHP_MEMORY_LIMIT=2G
      - PHP_OPCACHE_MEMORY_CONSUMPTION=512
      - PHP_OPCACHE_MAX_ACCELERATED_FILES=60000
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=0
      - PHP_OPCACHE_ENABLE_FILE_OVERRIDE=0
      - PHP_OPCACHE_HUGE_CODE_PAGES=1
      - PHP_REALPATH_CACHE_SIZE=10M
      - PHP_REALPATH_CACHE_TTL=7200
      - COMPOSER_MEMORY_LIMIT=2G
    volumes:
      - magento_data:/var/www/html
      - ./src:/var/www/html/app/code
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./php.ini:/usr/local/etc/php/conf.d/zz-magento.ini:ro
    depends_on:
      - mysql
      - redis_session
      - redis_cache
      - elasticsearch
    networks:
      - magento_network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 3G
        reservations:
          cpus: '1'
          memory: 2G

  nginx:
    image: nginx:alpine
    container_name: magento_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - magento_data:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - magento
    networks:
      - magento_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

YAML;
    }

    private function getDockerComposeRedis(): string
    {
        return <<<'YAML'

  redis_session:
    image: redis:7-alpine
    container_name: magento_redis_session
    command: >
      redis-server
      --maxmemory 1gb
      --maxmemory-policy allkeys-lru
      --save ""
      --appendonly no
      --tcp-keepalive 60
      --timeout 0
      --tcp-backlog 511
      --lazyfree-lazy-eviction yes
      --lazyfree-lazy-expire yes
      --lazyfree-lazy-server-del yes
      --loglevel warning
      --slowlog-log-slower-than 10000
      --slowlog-max-len 128
    volumes:
      - redis_session_data:/data
    networks:
      - magento_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1.5G
        reservations:
          memory: 1G

  redis_cache:
    image: redis:7-alpine
    container_name: magento_redis_cache
    command: >
      redis-server
      --maxmemory 2gb
      --maxmemory-policy allkeys-lru
      --save "900 1 300 10 60 10000"
      --tcp-keepalive 60
      --timeout 0
      --tcp-backlog 511
      --lazyfree-lazy-eviction yes
      --lazyfree-lazy-expire yes
      --loglevel warning
      --port 6380
    volumes:
      - redis_cache_data:/data
    networks:
      - magento_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2.5G
        reservations:
          memory: 2G

YAML;
    }

    private function getDockerComposeDatabase(): string
    {
        return <<<'YAML'

  mysql:
    image: mysql:8.0
    container_name: magento_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=magento123
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento123
    command: >
      --max_connections=500
      --innodb_buffer_pool_size=2G
      --innodb_log_file_size=512M
      --innodb_flush_log_at_trx_commit=2
      --innodb_flush_method=O_DIRECT
      --innodb_file_per_table=1
      --slow_query_log=1
      --slow_query_log_file=/var/log/mysql/slow.log
      --long_query_time=2
      --log_queries_not_using_indexes=1
      --max_allowed_packet=64M
      --sort_buffer_size=2M
      --read_buffer_size=2M
      --read_rnd_buffer_size=8M
      --join_buffer_size=8M
      --thread_cache_size=50
      --table_open_cache=4000
      --table_definition_cache=2000
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_logs:/var/log/mysql
    networks:
      - magento_network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 3G
        reservations:
          cpus: '1'
          memory: 2G

YAML;
    }

    private function getDockerComposeElasticsearch(): string
    {
        return <<<'YAML'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: magento_elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=magento-cluster
      - node.name=magento-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - indices.memory.index_buffer_size=30%
      - indices.queries.cache.size=15%
      - indices.fielddata.cache.size=25%
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - magento_network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G

YAML;
    }

    private function getDockerComposeVarnish(): string
    {
        return <<<'YAML'

  varnish:
    image: varnish:7.3-alpine
    container_name: magento_varnish
    ports:
      - "8080:80"
    volumes:
      - ./varnish.vcl:/etc/varnish/default.vcl:ro
    command: >
      -f /etc/varnish/default.vcl
      -s malloc,1g
      -p default_ttl=86400
      -p default_grace=86400
      -p feature=+esi_ignore_https
      -p thread_pools=4
      -p thread_pool_min=50
      -p thread_pool_max=1000
      -p thread_pool_add_delay=2
      -p cli_timeout=25
      -p workspace_backend=256k
      -p http_resp_hdr_len=65536
      -p http_resp_size=98304
    depends_on:
      - nginx
    networks:
      - magento_network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1.5G
        reservations:
          cpus: '0.5'
          memory: 1G

YAML;
    }

    private function getDockerComposeNetworks(): string
    {
        return <<<'YAML'

networks:
  magento_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

YAML;
    }

    private function getDockerComposeVolumes(): string
    {
        return <<<'YAML'

volumes:
  magento_data:
    driver: local
  mysql_data:
    driver: local
  mysql_logs:
    driver: local
  elasticsearch_data:
    driver: local
  redis_session_data:
    driver: local
  redis_cache_data:
    driver: local

YAML;
    }

    private function hasRecommendations(string ...$areas): bool
    {
        foreach ($this->recommendations as $rec) {
            if (in_array($rec->getArea(), $areas)) {
                return true;
            }
        }
        return false;
    }

    private function getRedisConfig(): array
    {
        // Extract Redis configuration from recommendations
        $config = [
            'disable_locking' => '1',
            'compression' => 'lz4',
            'persistent' => true,
            'timeout' => '2.5'
        ];

        foreach ($this->recommendations as $rec) {
            if ($rec->getArea() === 'redis') {
                // Parse recommendation details to extract specific config
                if (str_contains($rec->getMessage(), 'disable_locking')) {
                    $config['disable_locking'] = '1';
                }
            }
        }

        return $config;
    }
}
